apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: devops-demo
spec:
  selector:
    app: devops-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80