server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy to the Node.js container using its service name
    location /app/ {
        proxy_pass http://app:3000/;
    }
}